framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/bundles/easyadmin/manifest.json'
        packages:
            user_contracts:
                base_path: '%app.path.user_contracts%'
