#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  entities:
    - App\Entity\Genus
    - App\Entity\GenusNote
    - App\Entity\SubFamily
    - App\Entity\User