#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  site_name: Aqua<i>Note</i>
  design:
    brand_color: '#1ABC9C'
    assets:
      css:
        - 'css/custom_backend.css'
        #- '/bundles/easyadmin/bootstrap-all.css'
      js:
        #- /bundles\/easyadmin/bootstrap-all.js
        - https://unpkg.com/snarkdown@1.2.2/dist/snarkdown.umd.js
        - /js/custom_backend.js
    templates:
      field_id: 'admin/fields/_id.html.twig'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - 'Form/_form_theme.html.twig'
      - '@EasyAdmin/default/my_form_theme.html.twig'
    menu:
      - { label: Dashboard, route: admin_dashboard, defaul: true}
      - { entity: Genus }
      - { entity: GenusHorde }
      - { entity: GenusNote }
      - { entity: User }
  entities:
    Genus:
      class: App\Entity\Genus
      controller: genus_controller_service
      label: 'List of Genuses'
    GenusHorde:
      class: App\Entity\Genus
    GenusNote:
      class: App\Entity\GenusNote
    User:
      class: App\Entity\User