# config/routes/easy_admin.yaml
easy_admin_bundle:
    resource: 'Controller/AdminController.php'
    #resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation