#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#homepage:
#  path: /
#  defaults:
#    _controller: App\Controller\MainController::homepageAction

security_logout:
  path: /logout
  methods: GET