# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en_US'
    env(easyadmin_prefix): "/easyadmin"
    easyadmin_prefix: '%env(easyadmin_prefix)%'
    cache_type: file_system

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }
    App\DataFixtures\ORM\LoadFixtures:
        tags:
            - { name: nelmio_alice.faker.provider }
    App\Service\MarkdownTransformer:
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']


    admin.category:
        class: App\SonataAdmin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
        class: App\SonataAdmin\BlogPostAdmin
        arguments: [~, App\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Blog post' }








